### PR TITLE
Building on Linux

### PR DESCRIPTION
**Pull request by Murmele**
Not yet finish.

```
build-mdflib-Desktop-Debug/_deps/utillib-src/src/listenconfig.cpp:47: Fehler: no viable constructor or deduction guide for deduction of template arguments of 'scoped_lock'
build-mdflib-Desktop-Debug/_deps/utillib-src/src/listenconfig.cpp:47:17: error: no viable constructor or deduction guide for deduction of template arguments of 'scoped_lock'
    scoped_lock lock(config->locker);
                ^
/usr/include/boost/interprocess/interprocess_fwd.hpp:201:7: note: candidate template ignored: could not match 'scoped_lock<Mutex>' against 'boost::interprocess::interprocess_recursive_mutex'
class scoped_lock;
      ^
/usr/include/boost/interprocess/interprocess_fwd.hpp:201:7: note: candidate function template not viable: requires 0 arguments, but 1 was provided
```

### CODE REVIEW

**Review by ihedvall — COMMENTED** [review]
The IEquals should ignore case so the replacement is not correct

**Comment by Murmele** [comment]
> The IEquals should ignore case so the replacement is not correct

What do you mean?

**Comment by ihedvall** [comment]
It looks like you changed stricmp() with strcmp() function. The latter doesn't ignore case characters.

**Comment by Murmele** [comment]
> It looks like you changed stricmp() with strcmp() function. The latter doesn't ignore case characters.

Thank you I will change.

```
/home/martin/GIT/utillib/src/messagequeue.cpp:74: Fehler: no viable constructor or deduction guide for deduction of template arguments of 'scoped_lock'
/home/martin/GIT/utillib/src/messagequeue.cpp:74:19: error: no viable constructor or deduction guide for deduction of template arguments of 'scoped_lock'
      scoped_lock lock(mem.locker);
                  ^
/usr/include/boost/interprocess/interprocess_fwd.hpp:201:7: note: candidate template ignored: could not match 'scoped_lock<Mutex>' against 'boost::interprocess::interprocess_recursive_mutex'
class scoped_lock;
      ^
/usr/include/boost/interprocess/interprocess_fwd.hpp:201:7: note: candidate function template not viable: requires 0 arguments, but 1 was provided
```

**Comment by Murmele** [comment]
> It looks like you changed stricmp() with strcmp() function. The latter doesn't ignore case characters.

I fixed this again

**Review by ihedvall — APPROVED** [review]

**Review by ihedvall — APPROVED** [review]

**Comment by ihedvall** [comment]
Regarding the scoped_lock issue.

Sometimes the compilers get confused when using templates. the boost scoped lock is a template class so adding the mutex typename, may solve the problem. 

`scoped_lock lock(mem.locker);`
to
`scoped_lock<boost::interprocess::interprocess_recursive_mutex> lock(mem.locker);`

**Comment by ihedvall** [comment]
The builds doesn't find the boost root directory. Set the cmake 'Boost_ROOT' to the (yaml) boost install dir might work.

**Comment by Murmele** [comment]
````
 -- Boost Found (Try 1): TRUE
-- Boost Version: 1.74.0
-- Boost Include Dirs: /usr/include
-- Boost Library Dirs: /usr/lib/x86_64-linux-gnu
-- Boost Libraries: Boost::filesystemBoost::systemBoost::localeBoost::program_options
-- Boost Root: 
````
True the boost root is not se

**Comment by ihedvall** [comment]
Note that boost 1.74.0 is very old. The current version is 1.80.0.

**Comment by Murmele** [comment]
Did I oversee it or are the boost libraries not linked?

**Comment by Murmele** [comment]
> Regarding the scoped_lock issue.
> 
> Sometimes the compilers get confused when using templates. the boost scoped lock is a template class so adding the mutex typename, may solve the problem.
> 
> `scoped_lock lock(mem.locker);` to `scoped_lock<boost::interprocess::interprocess_recursive_mutex> lock(mem.locker);`

The problem was that it found only the declaration of scoped_lock but not the definition.
After including #include <boost/interprocess/sync/scoped_lock.hpp>
the error is gone.

I think boost root is only relevant for windows, because on linux there does not exist a boost root (or maybe /usr/) but it is only used to find the library and the succeded above.

**Comment by Murmele** [comment]
```
FAILED: listenviewer/listenviewer 
: && /usr/bin/clang++ -DQT_QML_DEBUG -pthread -g  listenviewer/CMakeFiles/listenviewer.dir/src/listenviewer.cpp.o listenviewer/CMakeFiles/listenviewer.dir/src/mainframe.cpp.o listenviewer/CMakeFiles/listenviewer.dir/src/settingdialog.cpp.o listenviewer/CMakeFiles/listenviewer.dir/src/listendialog.cpp.o listenviewer/CMakeFiles/listenviewer.dir/src/listenlistview.cpp.o -o listenviewer/listenviewer  libutild.a  /usr/lib/libexpat.so  -pthread  -lwx_gtk3u_core-3.2  -lwx_baseu-3.2  /usr/lib/libboost_filesystem.a  /usr/lib/libboost_system.a  /usr/lib/libboost_locale.a  /usr/lib/libboost_program_options.a  /usr/lib/libboost_atomic.a  /usr/lib/libboost_system.a  -licudata  -licui18n  -licuuc  /usr/lib/libboost_chrono.a  /usr/lib/libboost_thread.a && :
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64/Scrt1.o: in function `_start':
/build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:103: undefined reference to `main'
```
listenviewer does not have a main or?

**Comment by Murmele** [comment]
Would it be possible to move generated files into the build folder and include from there? So that they are not tracked with git?
image

**Comment by Murmele** [comment]
Is it intended to use a variable on stack than on heap?
image

**Comment by ihedvall** [comment]
The wxwidgets is little bit strange regarding the main vs WinMain problem. I had the opposite problem of not finding WinMain. The solution was to add to add a ` target_link_options(listenviewer PRIVATE /SUBSYSTEM:WINDOWS)`. I don't have a good solution but someone on the web should know.

**Comment by ihedvall** [comment]
Yes I know that wxwidgets always use the heap but for ImageList there is 2 ways to handle the ownership problem. So either as class member or on the heap. The first is needed if you need to reference the images lare on. The code should work.

**Comment by Murmele** [comment]
> The wxwidgets is little bit strange regarding the main vs WinMain problem. I had the opposite problem of not finding WinMain. The solution was to add to add a ` target_link_options(listenviewer PRIVATE /SUBSYSTEM:WINDOWS)`. I don't have a good solution but someone on the web should know.

Ok I will check

**Comment by Murmele** [comment]
> Yes I know that wxwidgets always use the heap but for ImageList there is 2 ways to handle the ownership problem. So either as class member or on the heap. The first is needed if you need to reference the images lare on. The code should work.

The problem was that wxIMPLEMENT_APP was within the namespace, which seems to make problems building on linux.

**Comment by ihedvall** [comment]
Nice catch with the wxwidgets::main() problem.

I think there will be some bitmap/image problem when running GUI with unix (linux and mac).

I'm setting up a Linux (ubuntu) development computer but I guess it will take some time before it works.

**Comment by Murmele** [comment]
> 

Yes I have seen. Now I am able to build the application but yes there is an issue not finding the images

**Comment by Murmele** [comment]
I think this is ready for now

**Pull request merged**
